### ISSUE TITLE
Project Creator may set up stripe credentials to receive payments

### ISSUE THREAD

**Issue by zspencer** [wecohere/nourish.party#10]
As a project creator
I want to receive money
So that I can pay rent, or at least buy a pizza occasionally.

Given I am logged in as a project creator
When I connect my Nourish account to my Stripe account
Then my Nourish account should be connected to my Stripe account

**Comment by bhaibel** [comment]
Updated description to be not empty. Improvements welcome to my story and scenario descriptions.

**Comment by zspencer** [comment]
In general, `then` statements that rephrase `when` are not super useful; instead could we use the `then my project is able to accept credit card payments via stripe`

I think this does two things:

1. It disambiguates Stripe connections from the project and creator. For instance, I could have a Zee's Sounds project, which is my amazing tunes and payments go into my personal bank account, and a nourish.party project, where payments go into Cohere's bank account, and <insert other project here> which could be a completely different entity.
2. It adds a broader word-pool per statement. This (theoretically) reduces the amount of ambiguity, since it gives more things to reflect on when doing the implementation.

Seem reasonable?

**Comment by bhaibel** [comment]
I agree with you about the uselessness of Thens that rephrase a When. I'm having a hard time thinking of a When that doesn't make this story ENORMOUS -- like, what are you visualizing for how we test `then my project is able to accept credit card payments via stripe` ?

**Comment by zspencer** [comment]
That a predicate function returns true for now, we can flesh out the actually accepting payments in a different ticket
