### ISSUE TITLE
RFC: What words should we describe creators/backers?

### ISSUE THREAD

**Issue by zspencer** [wecohere/nourish.party#3]
The questions in my head right now are:

1. Are there specific words that we shouldn't use (i.e. donors seems like it would restrict to non profits?)
2. Are there specific words that are more aligned with our "brand" guide (Optimistic, upbeat, independent, community focused)
3.  Are there words that we're more excited about than others?

**Comment by bhaibel** [comment]
We seem to have converged around using plain language like "creator" and "supporter" internally. Closing this RFC, not to close discussion, but to reflect that we have a working consensus & that if we want to change that consensus we should probably open a new RFC.
