### ISSUE TITLE
RFC: What is Nourish.Party's system diagram?

### ISSUE THREAD

**Issue by zspencer** [wecohere/nourish.party#38]
There's probably some miscommunications between all of us about how the system *should* work. @bhaibel - if you want to take a swag at drawing a system diagram it may be useful to have that before we open-source and start soliciting contributions.

The questions that may be most useful to answer in the short term are:

1. How does a nourish.party instance integrate with content hosts, such as wordpress or discord? 
2. Are there particular webhooks we want to expose, and if so, what are they? 
3. Are there particular existing RFCs or standards that we'd want to base the nourish.party protocol off of?
4. Do we have some basic idea for the different entities we expect to exist in the MVP system? If so, what are they and how do they interact/relate to one another? (Especially if we're missing some "pseudo-entities" that aren't obvious)
4. ??? I don't know ??? 

Thoughts @bhaibel / @emdashbuck / @jtu0 ?

**Comment by bhaibel** [comment]
![img_3462](https://user-images.githubusercontent.com/302044/34278767-e99bc4ca-e67a-11e7-93fa-ac5354e9cd34.JPG)

**Comment by zspencer** [comment]
Looks great! Can we get this into the repo under `/design` or `/doc` or something? (Or is `doc` reserved by `yard`?)

**Comment by zspencer** [comment]
Also may want to take pictures closer up of the different sections, so that it's a touch easier to read at lower resolution.
