### ISSUE TITLE
Forms align their "next" action to the right and their "other actions" to the left

### ISSUE THREAD

**Issue by zspencer** [wecohere/nourish.party#75]
In order to have a consistent experience of flow across forms
As a user I would like the buttons to submit a form be on the bottom right, with additional data or actions aligned to the left

Ideally, this would be done in such a way that if a users language reads LTR we invert the order; but I have no idea how to CSS Grid :x

**Comment by bhaibel** [comment]
This might be a flexbox thing tbh: one way to think about when to use flexbox vs grid is that flexbox is for arranging things along a single dimension, and grid is for arranging them in two dimensions.

**Comment by zspencer** [comment]
Resolved by https://github.com/wecohere/nourish.party/pull/90
